export const SAD = [
  "I don't know what to do anymore.",
  "Can't wait for my next rejection!",
  "I can't catch a break.",
  "Losing hope :)",
  "Think I'm going to spend my entire day applying again and be trash aha",
  "Still trying my best.",
  "It's hard to keep going when it feels like no one wants me.",
  "I'm just a failure.",
  "it's hard to stop",
  "i'm not good enough",
  "I don't know what to do.",
  "tired",
  "Isn't it easier to give up?",
  "Feels like I've been applying for months",
  "a burden and a bother",
  "Gotta broaden my search",
  "Think I'll look into other related positions today",
  "Do personal projects matter?",
  "should practice interviewing",
  "Maybe I should become a friend of a friend who's uncle's friend's daughter knows someone who knows someone else...",
  "wake up, apply, sleep",
  "aosidhjasiodajdoiaiodjaosd",
  "going insane",
  "bout to go big mode today",
];

export const SUPPORT = [
  "Good luck today.",
  "Do your best!",
  "Don't give up you weakling >:(",
  "You got this easily.",
  "It's their loss they skipped you",
  "Just make sure to take care of yourself.",
  "Hope you're doing okay.",
  "Thinking about you.",
  "A job search doesn't define your worth. Money does! jk",
  "Don't worry, it's just a numbers game at this point!",
  "Job fair today?",
  "Try to reach out to others?",
  "Other job boards could be good!",
  "aeiklufyaehrfiuwehnfkjaf",
  "How's job hunting going?",
  "You'll find something soon, I know it!",
];
